export const ADD_FURNITURE_TO_CART = 'ADD_FURNITURE_TO_CART';
export type ADD_FURNITURE_TO_CART = typeof ADD_FURNITURE_TO_CART;

export const INCREASE_FURNITURE_AMOUNT = 'INCREASE_FURNITURE_AMOUNT';
export type INCREASE_FURNITURE_AMOUNT = typeof INCREASE_FURNITURE_AMOUNT;

export const DECREASE_FURNITURE_AMOUNT = 'DECREASE_FURNITURE_AMOUNT';
export type DECREASE_FURNITURE_AMOUNT = typeof DECREASE_FURNITURE_AMOUNT;

export const DELETE_FURNITURE_FROM_CART = 'DELETE_FURNITURE_FROM_CART';
export type DELETE_FURNITURE_FROM_CART = typeof DELETE_FURNITURE_FROM_CART;
