export const SET_FURNITURE_LOAD_STATUS = 'SET_FURNITURE_LOAD_STATUS';
export type SET_FURNITURE_LOAD_STATUS = typeof SET_FURNITURE_LOAD_STATUS;

export const SET_FURNITURE = 'SET_FURNITURE';
export type SET_FURNITURE = typeof SET_FURNITURE;
