export const SET_FURNITURE_TYPES_LOAD_STATUS =
  'SET_FURNITURE_TYPES_LOAD_STATUS';
export type SET_FURNITURE_TYPES_LOAD_STATUS = typeof SET_FURNITURE_TYPES_LOAD_STATUS;

export const SET_FURNITURE_TYPES = 'SET_FURNITURE_TYPES';
export type SET_FURNITURE_TYPES = typeof SET_FURNITURE_TYPES;

export const SET_CURRENT_FURNITURE_TYPE = 'SET_CURRENT_FURNITURE_TYPE';
export type SET_CURRENT_FURNITURE_TYPE = typeof SET_CURRENT_FURNITURE_TYPE;
